[package]
name = "jargonoc"
version = "0.1.0"
authors = ["Bobbbay <abatterysingle@gmail.com>"]
edition = "2018"

[dependencies]
# Parser
peg = "0.7.0"
chic = "1.2.2"

# Codegen
llvm = { package = "llvm-sys", version = "100" }